version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - security_tedas_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - security_tedas_network

#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     networks:
#       - security_tedas_network
#     depends_on:
#       - db

networks:
  security_tedas_network:
    driver: bridge